# SPDX-FileCopyrightText: 2025 GoobBot <uristmchands@proton.me>
# SPDX-FileCopyrightText: 2025 pheenty <fedorlukin2006@gmail.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

- type: loadout
  id: HeadofSecurityVestWeb
  equipment:
    outerClothing: ClothingOuterArmorHoSVestWeb

- type: loadout
  id: HeadofSecuritySpecialBeret
  equipment:
    head: ClothingHeadHatBeretHeadOfSecurityAdvanced

- type: loadout
  id: HeadofSecurityGreatCoat
  equipment:
    outerClothing: ClothingOuterArmorHoSExperimental

- type: loadout
  id: AdvancedJackBoots
  equipment:
    shoes: ClothingShoesBootsJackAdvancedFilled

- type: loadout
  id: HeadofSecurityEnvirosuit
  equipment:
    jumpsuit: ClothingUniformEnvirosuitHoS
  effects:
  - !type:SpeciesLoadoutEffect # Goobstation - EE Plasmeme Change.
    species:
    - Plasmaman

- type: loadout
  id: HeadofSecurityEnvirohelm
  equipment:
    head: ClothingHeadEnvirohelmHoS
  effects:
  - !type:SpeciesLoadoutEffect # Goobstation - EE Plasmeme Change.
    species:
    - Plasmaman
